export const CLIENT_ID = "32IXSTBK1V3NFIH3NFJ5LZHYWKKSNA131CZR0RFCE2OTRERJ";
export const CLIENT_SECRET = "0SVNBULCMHEUOY3ZXSGPVJ3XDQN5EYNZRXOXHNIU2AOVO10Q";
export const API_KEY = "pk.eyJ1IjoibDByZGNhZmUiLCJhIjoiY2prZTNuMmxlM3doMzNxbXF6OTRqY2JhayJ9.A2kHrrLrGOXviTolAByyIA";
